Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.ssh.insert_key = false

  config.vm.define "yobenaliS" do |server|
    server.vm.hostname = "yobenaliS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.boot_timeout = 600

    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus   = 1
      vb.name   = "yobenaliS-p2"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.customize ["modifyvm", :id, "--usb", "off"]
      vb.customize ["modifyvm", :id, "--paravirtprovider", "kvm"]
    end

    server.vm.provision "shell", path: "scripts/install.sh"
  end
end