Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "yobenaliS" do |server|
    server.vm.hostname = "yobenaliS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.boot_timeout = 600

    server.vm.provider "virtualbox" do |vb|
      vb.name   = "yobenaliS"
      vb.memory = "1024"
      vb.cpus   = 1
    end

    server.vm.provision "shell", path: "scripts/install.sh"
  end
end