Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.ssh.insert_key = false

  # ─── Server Node (Controller Mode) ───────────────────────────────────────────
  config.vm.define "yobenaliS" do |server|
    server.vm.hostname = "yobenaliS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.boot_timeout = 600

    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus   = 1
      vb.name   = "yobenaliS"
    end

    server.vm.provision "shell", path: "scripts/server.sh"
  end

  # ─── Worker Node (Agent Mode) ─────────────────────────────────────────────────
  config.vm.define "yobenaliSW" do |worker|
    worker.vm.hostname = "yobenaliSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.boot_timeout = 600

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus   = 1
      vb.name   = "yobenaliSW"
    end

    worker.vm.provision "shell", path: "scripts/worker.sh"
  end

end