Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "yobenaliS" do |server|
    server.vm.hostname = "yobenaliS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
      vb.name = "yobenaliS"
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    end

    server.vm.provision "file", source: "scripts/install_k3s.sh", destination: "/tmp/install_k3s.sh"
    server.vm.provision "shell", inline: "chmod +x /tmp/install_k3s.sh && /tmp/install_k3s.sh server"
  end

  config.vm.define "yobenaliSW" do |worker|
    worker.vm.hostname = "yobenaliSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
      vb.name = "yobenaliSW"
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    end

    worker.vm.provision "file", source: "scripts/install_k3s.sh", destination: "/tmp/install_k3s.sh"
    worker.vm.provision "shell", inline: "chmod +x /tmp/install_k3s.sh && /tmp/install_k3s.sh agent 192.168.56.110"
  end
end
